//
// Core domain type definitions for the College Bus Management System.
// PUBLIC_INTERFACE: This module exposes all core domain interfaces and utility types.
//
// Notes:
// - All IDs are string UUID-like identifiers (can be generated by services).
// - Time values are stored as ISO 8601 strings unless specified otherwise.
// - Optional fields are marked where appropriate to keep flexibility for mock/demo.
//

// PUBLIC_INTERFACE
export type ID = string;

// PUBLIC_INTERFACE
export type EntityKind = 'bus' | 'route' | 'driver' | 'schedule' | 'seat' | 'booking';

// PUBLIC_INTERFACE
export interface BaseEntity {
  /** Unique identifier string */
  id: ID;
  /** Creation ISO date */
  createdAt: string;
  /** Update ISO date */
  updatedAt: string;
}

// PUBLIC_INTERFACE
export interface Route extends BaseEntity {
  kind: 'route';
  name: string;
  /** Human readable list of stops in order */
  stops: string[];
  /** First bus time (HH:mm) */
  firstBusTime: string;
  /** Last bus time (HH:mm) */
  lastBusTime: string;
  /** Optional notes or description */
  description?: string;
  /** Typically 'active' or 'inactive' for basic filtering */
  status: 'active' | 'inactive';
}

// PUBLIC_INTERFACE
export interface Driver extends BaseEntity {
  kind: 'driver';
  fullName: string;
  phone?: string;
  licenseNumber?: string;
  /** If a driver is currently on-duty */
  active: boolean;
}

// PUBLIC_INTERFACE
export interface Bus extends BaseEntity {
  kind: 'bus';
  code: string; // e.g., "Bus 12"
  capacity: number; // total seats
  /** Optional link to assigned driver */
  driverId?: ID | null;
  /** Route the bus primarily serves */
  routeId?: ID | null;
  status: 'active' | 'maintenance' | 'inactive';
}

// PUBLIC_INTERFACE
export interface Schedule extends BaseEntity {
  kind: 'schedule';
  /** Bus that runs this schedule */
  busId: ID;
  /** Route this schedule belongs to */
  routeId: ID;
  /** ISO 8601 date string for the service day (e.g., "2025-01-30") */
  serviceDate: string;
  /** Start time (HH:mm) */
  startTime: string;
  /** End time (HH:mm) */
  endTime: string;
  /** Optional recurrence information; for demo we keep it simple */
  recurrence?: 'none' | 'daily' | 'weekday' | 'weekend';
}

// PUBLIC_INTERFACE
export interface Seat extends BaseEntity {
  kind: 'seat';
  busId: ID;
  /** Human-readable seat number, e.g., "1A" */
  number: string;
  /** If seat is currently reserved for a given schedule window */
  status: 'available' | 'reserved' | 'blocked';
  /** Optional lock for a specific schedule instance */
  scheduleId?: ID | null;
}

// PUBLIC_INTERFACE
export interface Booking extends BaseEntity {
  kind: 'booking';
  /** Student ID (free-form, captured via form) */
  studentId: string;
  routeId: ID;
  busId: ID;
  /** Optional seatId (if seat selection is supported) */
  seatId?: ID | null;
  scheduleId: ID;
  /** Date for travel as ISO date string "YYYY-MM-DD" */
  travelDate: string;
  status: 'pending' | 'confirmed' | 'cancelled';
  /** Extra info like created from student portal, etc. */
  notes?: string;
}

// PUBLIC_INTERFACE
export interface DataEnvelope {
  version: number;
  lastUpdated: string;
  routes: Route[];
  drivers: Driver[];
  buses: Bus[];
  schedules: Schedule[];
  seats: Seat[];
  bookings: Booking[];
}

// PUBLIC_INTERFACE
export interface Pagination {
  page: number;
  pageSize: number;
}

// PUBLIC_INTERFACE
export interface PagedResult<T> {
  items: T[];
  total: number;
  page: number;
  pageSize: number;
}

// PUBLIC_INTERFACE
export type PartialEntityMap = Partial<{
  routes: Partial<Route>;
  drivers: Partial<Driver>;
  buses: Partial<Bus>;
  schedules: Partial<Schedule>;
  seats: Partial<Seat>;
  bookings: Partial<Booking>;
}>;

// PUBLIC_INTERFACE
export type CollectionKey = keyof Pick<DataEnvelope, 'routes' | 'drivers' | 'buses' | 'schedules' | 'seats' | 'bookings'>;
